name: Dev Environment Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "."

      - name: Create Pull Request to QA
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge dev into qa"
          title: "Pull Request: Merge dev into qa"
          body: "This PR merges the changes from dev into qa."
          base: qa
          head: dev
          branch: dev-to-qa-automated-pr